export const countryCurrencyMap: Record<string, { currency: string; symbol: string }> = {
  "Afghanistan": { currency: "AFN", symbol: "؋" },
  "Albania": { currency: "ALL", symbol: "L" },
  "Algeria": { currency: "DZD", symbol: "د.ج" },
  "Andorra": { currency: "EUR", symbol: "€" },
  "Angola": { currency: "AOA", symbol: "Kz" },
  "Argentina": { currency: "ARS", symbol: "$" },
  "Armenia": { currency: "AMD", symbol: "֏" },
  "Australia": { currency: "AUD", symbol: "$" },
  "Austria": { currency: "EUR", symbol: "€" },
  "Azerbaijan": { currency: "AZN", symbol: "₼" },
  "Bahamas": { currency: "BSD", symbol: "$" },
  "Bahrain": { currency: "BHD", symbol: ".د.ب" },
  "Bangladesh": { currency: "BDT", symbol: "৳" },
  "Barbados": { currency: "BBD", symbol: "$" },
  "Belarus": { currency: "BYN", symbol: "Br" },
  "Belgium": { currency: "EUR", symbol: "€" },
  "Belize": { currency: "BZD", symbol: "$" },
  "Benin": { currency: "XOF", symbol: "Fr" },
  "Bhutan": { currency: "BTN", symbol: "Nu." },
  "Bolivia": { currency: "BOB", symbol: "Bs" },
  "Bosnia and Herzegovina": { currency: "BAM", symbol: "KM" },
  "Botswana": { currency: "BWP", symbol: "P" },
  "Brazil": { currency: "BRL", symbol: "R$" },
  "Brunei": { currency: "BND", symbol: "$" },
  "Bulgaria": { currency: "BGN", symbol: "лв" },
  "Burkina Faso": { currency: "XOF", symbol: "Fr" },
  "Burundi": { currency: "BIF", symbol: "Fr" },
  "Cambodia": { currency: "KHR", symbol: "៛" },
  "Cameroon": { currency: "XAF", symbol: "Fr" },
  "Canada": { currency: "CAD", symbol: "$" },
  "Cape Verde": { currency: "CVE", symbol: "$" },
  "Central African Republic": { currency: "XAF", symbol: "Fr" },
  "Chad": { currency: "XAF", symbol: "Fr" },
  "Chile": { currency: "CLP", symbol: "$" },
  "China": { currency: "CNY", symbol: "¥" },
  "Colombia": { currency: "COP", symbol: "$" },
  "Comoros": { currency: "KMF", symbol: "Fr" },
  "Congo": { currency: "XAF", symbol: "Fr" },
  "Costa Rica": { currency: "CRC", symbol: "₡" },
  "Croatia": { currency: "EUR", symbol: "€" },
  "Cuba": { currency: "CUP", symbol: "₱" },
  "Cyprus": { currency: "EUR", symbol: "€" },
  "Czech Republic": { currency: "CZK", symbol: "Kč" },
  "Denmark": { currency: "DKK", symbol: "kr" },
  "Djibouti": { currency: "DJF", symbol: "Fr" },
  "Dominica": { currency: "XCD", symbol: "$" },
  "Dominican Republic": { currency: "DOP", symbol: "$" },
  "Ecuador": { currency: "USD", symbol: "$" },
  "Egypt": { currency: "EGP", symbol: "£" },
  "El Salvador": { currency: "USD", symbol: "$" },
  "Equatorial Guinea": { currency: "XAF", symbol: "Fr" },
  "Eritrea": { currency: "ERN", symbol: "Nfk" },
  "Estonia": { currency: "EUR", symbol: "€" },
  "Ethiopia": { currency: "ETB", symbol: "Br" },
  "Fiji": { currency: "FJD", symbol: "$" },
  "Finland": { currency: "EUR", symbol: "€" },
  "France": { currency: "EUR", symbol: "€" },
  "Gabon": { currency: "XAF", symbol: "Fr" },
  "Gambia": { currency: "GMD", symbol: "D" },
  "Georgia": { currency: "GEL", symbol: "₾" },
  "Germany": { currency: "EUR", symbol: "€" },
  "Ghana": { currency: "GHS", symbol: "₵" },
  "Greece": { currency: "EUR", symbol: "€" },
  "Grenada": { currency: "XCD", symbol: "$" },
  "Guatemala": { currency: "GTQ", symbol: "Q" },
  "Guinea": { currency: "GNF", symbol: "Fr" },
  "Guinea-Bissau": { currency: "XOF", symbol: "Fr" },
  "Guyana": { currency: "GYD", symbol: "$" },
  "Haiti": { currency: "HTG", symbol: "G" },
  "Honduras": { currency: "HNL", symbol: "L" },
  "Hong Kong": { currency: "HKD", symbol: "$" },
  "Hungary": { currency: "HUF", symbol: "Ft" },
  "Iceland": { currency: "ISK", symbol: "kr" },
  "India": { currency: "INR", symbol: "₹" },
  "Indonesia": { currency: "IDR", symbol: "Rp" },
  "Iran": { currency: "IRR", symbol: "﷼" },
  "Iraq": { currency: "IQD", symbol: "ܘ" },
  "Ireland": { currency: "EUR", symbol: "€" },
  "Israel": { currency: "ILS", symbol: "₪" },
  "Italy": { currency: "EUR", symbol: "€" },
  "Jamaica": { currency: "JMD", symbol: "$" },
  "Japan": { currency: "JPY", symbol: "¥" },
  "Jordan": { currency: "JOD", symbol: "د.ا" },
  "Kazakhstan": { currency: "KZT", symbol: "₸" },
  "Kenya": { currency: "KES", symbol: "Sh" },
  "Kiribati": { currency: "AUD", symbol: "$" },
  "Kosovo": { currency: "EUR", symbol: "€" },
  "Kuwait": { currency: "KWD", symbol: "د.ك" },
  "Kyrgyzstan": { currency: "KGS", symbol: "с" },
  "Laos": { currency: "LAK", symbol: "₭" },
  "Latvia": { currency: "EUR", symbol: "€" },
  "Lebanon": { currency: "LBP", symbol: "£" },
  "Lesotho": { currency: "LSL", symbol: "L" },
  "Liberia": { currency: "LRD", symbol: "$" },
  "Libya": { currency: "LYD", symbol: "ل.د" },
  "Liechtenstein": { currency: "CHF", symbol: "Fr" },
  "Lithuania": { currency: "EUR", symbol: "€" },
  "Luxembourg": { currency: "EUR", symbol: "€" },
  "Macao": { currency: "MOP", symbol: "P" },
  "Macedonia": { currency: "MKD", symbol: "ден" },
  "Madagascar": { currency: "MGA", symbol: "Ar" },
  "Malawi": { currency: "MWK", symbol: "MK" },
  "Malaysia": { currency: "MYR", symbol: "RM" },
  "Maldives": { currency: "MVR", symbol: "Rf" },
  "Mali": { currency: "XOF", symbol: "Fr" },
  "Malta": { currency: "EUR", symbol: "€" },
  "Marshall Islands": { currency: "USD", symbol: "$" },
  "Mauritania": { currency: "MRU", symbol: "UM" },
  "Mauritius": { currency: "MUR", symbol: "₨" },
  "Mexico": { currency: "MXN", symbol: "$" },
  "Micronesia": { currency: "USD", symbol: "$" },
  "Moldova": { currency: "MDL", symbol: "L" },
  "Monaco": { currency: "EUR", symbol: "€" },
  "Mongolia": { currency: "MNT", symbol: "₮" },
  "Montenegro": { currency: "EUR", symbol: "€" },
  "Morocco": { currency: "MAD", symbol: "د.م." },
  "Mozambique": { currency: "MZN", symbol: "MT" },
  "Myanmar": { currency: "MMK", symbol: "Ks" },
  "Namibia": { currency: "NAD", symbol: "$" },
  "Nauru": { currency: "AUD", symbol: "$" },
  "Nepal": { currency: "NPR", symbol: "₨" },
  "Netherlands": { currency: "EUR", symbol: "€" },
  "New Zealand": { currency: "NZD", symbol: "$" },
  "Nicaragua": { currency: "NIO", symbol: "C$" },
  "Niger": { currency: "XOF", symbol: "Fr" },
  "Nigeria": { currency: "NGN", symbol: "₦" },
  "North Korea": { currency: "KPW", symbol: "₩" },
  "Norway": { currency: "NOK", symbol: "kr" },
  "Oman": { currency: "OMR", symbol: "ر.ع." },
  "Pakistan": { currency: "PKR", symbol: "₨" },
  "Palau": { currency: "USD", symbol: "$" },
  "Palestine": { currency: "ILS", symbol: "₪" },
  "Panama": { currency: "PAB", symbol: "B/." },
  "Papua New Guinea": { currency: "PGK", symbol: "K" },
  "Paraguay": { currency: "PYG", symbol: "₲" },
  "Peru": { currency: "PEN", symbol: "S/" },
  "Philippines": { currency: "PHP", symbol: "₱" },
  "Poland": { currency: "PLN", symbol: "zł" },
  "Portugal": { currency: "EUR", symbol: "€" },
  "Qatar": { currency: "QAR", symbol: "ر.ق" },
  "Romania": { currency: "RON", symbol: "lei" },
  "Russia": { currency: "RUB", symbol: "₽" },
  "Rwanda": { currency: "RWF", symbol: "Fr" },
  "Saint Kitts and Nevis": { currency: "XCD", symbol: "$" },
  "Saint Lucia": { currency: "XCD", symbol: "$" },
  "Saint Vincent and the Grenadines": { currency: "XCD", symbol: "$" },
  "Samoa": { currency: "WST", symbol: "T" },
  "San Marino": { currency: "EUR", symbol: "€" },
  "Sao Tome and Principe": { currency: "STN", symbol: "Db" },
  "Saudi Arabia": { currency: "SAR", symbol: "ر.س" },
  "Senegal": { currency: "XOF", symbol: "Fr" },
  "Serbia": { currency: "RSD", symbol: "дин" },
  "Seychelles": { currency: "SCR", symbol: "₨" },
  "Sierra Leone": { currency: "SLL", symbol: "Le" },
  "Singapore": { currency: "SGD", symbol: "$" },
  "Slovakia": { currency: "EUR", symbol: "€" },
  "Slovenia": { currency: "EUR", symbol: "€" },
  "Solomon Islands": { currency: "SBD", symbol: "$" },
  "Somalia": { currency: "SOS", symbol: "Sh" },
  "South Africa": { currency: "ZAR", symbol: "R" },
  "South Korea": { currency: "KRW", symbol: "₩" },
  "South Sudan": { currency: "SSP", symbol: "£" },
  "Spain": { currency: "EUR", symbol: "€" },
  "Sri Lanka": { currency: "LKR", symbol: "Rs" },
  "Sudan": { currency: "SDG", symbol: "ج.س" },
  "Suriname": { currency: "SRD", symbol: "$" },
  "Sweden": { currency: "SEK", symbol: "kr" },
  "Switzerland": { currency: "CHF", symbol: "Fr" },
  "Syria": { currency: "SYP", symbol: "£" },
  "Taiwan": { currency: "TWD", symbol: "NT$" },
  "Tajikistan": { currency: "TJS", symbol: "ЅМ" },
  "Tanzania": { currency: "TZS", symbol: "Sh" },
  "Thailand": { currency: "THB", symbol: "฿" },
  "Timor-Leste": { currency: "USD", symbol: "$" },
  "Togo": { currency: "XOF", symbol: "Fr" },
  "Tonga": { currency: "TOP", symbol: "T$" },
  "Trinidad and Tobago": { currency: "TTD", symbol: "$" },
  "Tunisia": { currency: "TND", symbol: "د.ت" },
  "Turkey": { currency: "TRY", symbol: "₺" },
  "Turkmenistan": { currency: "TMT", symbol: "m" },
  "Tuvalu": { currency: "AUD", symbol: "$" },
  "Uganda": { currency: "UGX", symbol: "Sh" },
  "Ukraine": { currency: "UAH", symbol: "₴" },
  "United Arab Emirates": { currency: "AED", symbol: "د.إ" },
  "United Kingdom": { currency: "GBP", symbol: "£" },
  "United States": { currency: "USD", symbol: "$" },
  "Uruguay": { currency: "UYU", symbol: "$" },
  "Uzbekistan": { currency: "UZS", symbol: "сўм" },
  "Vanuatu": { currency: "VUV", symbol: "Vt" },
  "Vatican City": { currency: "EUR", symbol: "€" },
  "Venezuela": { currency: "VES", symbol: "Bs" },
  "Vietnam": { currency: "VND", symbol: "₫" },
  "Yemen": { currency: "YER", symbol: "﷼" },
  "Zambia": { currency: "ZMW", symbol: "ZK" },
  "Zimbabwe": { currency: "ZWL", symbol: "Z$" },
};

export const getCountries = (): string[] => {
  return Object.keys(countryCurrencyMap).sort();
};

export const getCurrencySymbol = (country: string): string => {
  return countryCurrencyMap[country]?.symbol || "$";
};

export const getCurrencyCode = (country: string): string => {
  return countryCurrencyMap[country]?.currency || "USD";
};
